### ISSUE TITLE
Bug in region setting?

### ISSUE THREAD

**Issue by nmchau** [wrangr/awis#27]
Thank you for this great library!

We currently use awis (v1.0.10) to query the sites by categories (Action: 'CategoryListings') in our project. 

We noticed that it only works with the 'us-west-1' region. With the other regions (e.g. us-west-2), we always receive the error messages as follows

```
Error: getaddrinfo ENOTFOUND awis.us-west-2.amazonaws.com awis.us-west-2.amazonaws.com:443
   at errnoException (dns.js:50:10)
   at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)
```

**Comment by dachinat** [comment]
Any solution?

**Comment by kevinstubbs** [comment]
Just ran into this exact error when setting the region to us-west-2. Looking at the AWIS documentation, I'm not sure that a region needs to be supplied at all, since the example request endpoint is simply `https://awis.amazonaws.com/api?Action=UrlInfo&ResponseGroup=[Valid Response Group]&Url=[Valid URL]`
https://docs.aws.amazon.com/AlexaWebInfoService/latest/ApiReference_UrlInfoAction.html

I wonder what the purpose of changing the region is - just to make sure the request stays within the same datacenter if running from within AWS (EC2, lambda, etc.)?
